-- Make a method that takse in a list of keybinds and applies them.
-- like so:
    --
    -- [1]: (string) lhs (required)
    -- [2]: (string|fun()) rhs (optional)
    -- mode: (string|string[]) mode (optional, defaults to "n")
    -- ft: (string|string[]) filetype for buffer-local keymaps (optional)
    -- any other option valid for vim.keymap.set
